# Generated by Django 5.2.11 on 2026-02-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountsAuditLog',
            new_name='AuditLogs',
        ),
    ]
