# Generated by Django 5.2.11 on 2026-02-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accountsauditlog_auditlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
