# Generated by Django 5.2.11 on 2026-02-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=1024)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('exclude_patterns', models.JSONField(blank=True, default=list)),
                ('algorithm_type', models.CharField(choices=[('sha256', 'SHA256'), ('sha512', 'SHA512'), ('blake3', 'BLAKE3')], default='sha256', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baselines', to='accounts.users')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaselineFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_name', models.CharField(db_index=True, max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('sha512', models.CharField(blank=True, max_length=128, null=True)),
                ('blake3', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.BigIntegerField()),
                ('permissions', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('inode', models.BigIntegerField()),
                ('hard_links', models.IntegerField()),
                ('mtime', models.FloatField()),
                ('atime', models.FloatField()),
                ('ctime', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_files', to='monitoring.baseline')),
            ],
            options={
                'ordering': ['file_path'],
            },
        ),
        migrations.CreateModel(
            name='FileChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_index=True, max_length=1024)),
                ('change_type', models.CharField(choices=[('created', 'File Created'), ('modified', 'File Modified'), ('deleted', 'File Deleted'), ('moved', 'File Moved'), ('permission_changed', 'Permission Changed'), ('ownership_changed', 'Ownership Changed')], max_length=50)),
                ('change_details', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, max_length=20)),
                ('expected', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_changes', to='monitoring.baseline')),
                ('baseline_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.baselinefile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.users')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('file_path', models.CharField(db_index=True, max_length=1024)),
                ('change_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('alert_channels', models.JSONField(default=list)),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ManyToManyField(blank=True, related_name='read_alerts', to='accounts.users')),
                ('file_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.filechange')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('files_scanned', models.PositiveIntegerField(default=0)),
                ('files_changed', models.PositiveIntegerField(default=0)),
                ('files_critical', models.PositiveIntegerField(default=0)),
                ('files_added', models.PositiveIntegerField(default=0)),
                ('files_deleted', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_sessions', to='monitoring.baseline')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.users')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_pattern', models.CharField(help_text='Glob pattern or regex', max_length=1024)),
                ('change_types', models.JSONField(default=list, help_text='List of allowed change types')),
                ('reason', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_rules', to='monitoring.baseline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.users')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='baseline',
            index=models.Index(fields=['name'], name='monitoring__name_87193c_idx'),
        ),
        migrations.AddIndex(
            model_name='baseline',
            index=models.Index(fields=['status'], name='monitoring__status_e1f8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='baseline',
            index=models.Index(fields=['created_at'], name='monitoring__created_575efa_idx'),
        ),
        migrations.AddIndex(
            model_name='baselinefile',
            index=models.Index(fields=['baseline', 'file_path'], name='monitoring__baselin_5d7df1_idx'),
        ),
        migrations.AddIndex(
            model_name='baselinefile',
            index=models.Index(fields=['sha256'], name='monitoring__sha256_dbeb24_idx'),
        ),
        migrations.AddIndex(
            model_name='baselinefile',
            index=models.Index(fields=['file_name'], name='monitoring__file_na_b7fb81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='baselinefile',
            unique_together={('baseline', 'file_path')},
        ),
        migrations.AddIndex(
            model_name='filechange',
            index=models.Index(fields=['baseline', 'detected_at'], name='monitoring__baselin_091b19_idx'),
        ),
        migrations.AddIndex(
            model_name='filechange',
            index=models.Index(fields=['file_path'], name='monitoring__file_pa_6ffe5d_idx'),
        ),
        migrations.AddIndex(
            model_name='filechange',
            index=models.Index(fields=['severity'], name='monitoring__severit_ef24f9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'created_at'], name='monitoring__severit_a72ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['read'], name='monitoring__read_48289d_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringsession',
            index=models.Index(fields=['baseline', 'start_time'], name='monitoring__baselin_edb342_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringsession',
            index=models.Index(fields=['status'], name='monitoring__status_ae0da3_idx'),
        ),
        migrations.AddIndex(
            model_name='whitelistrule',
            index=models.Index(fields=['baseline', 'active'], name='monitoring__baselin_e4a47e_idx'),
        ),
    ]
