# Generated by Django 5.2.11 on 2026-02-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsession',
            name='monitor_type',
            field=models.CharField(default='full', max_length=20),
        ),
    ]
