# Generated by Django 5.2.11 on 2026-02-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_monitoringsession_monitor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
