# Generated by Django 5.2.11 on 2026-02-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_id'),
        ('monitoring', '0003_monitoringsession_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_channels',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='baseline',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='baselinefile',
            name='blake3',
        ),
        migrations.AlterField(
            model_name='baseline',
            name='algorithm_type',
            field=models.CharField(choices=[('sha256', 'SHA256'), ('sha512', 'SHA512')], default='sha256', max_length=20),
        ),
        migrations.AlterField(
            model_name='baseline',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='baseline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.users'),
        ),
    ]
