# Generated by Django 5.2.11 on 2026-02-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_remove_alert_alert_channels_remove_alert_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='current_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
