# Generated by Django 5.2.11 on 2026-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_filechange_current_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_channels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
